### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by dented42**
I've done some general cleaning things.

- Redundant import statements have been removed.
- the stack.yaml has been updated to the latest lts release (8.18)
- Dependencies have been updated.
- Some more functions for visualising genomes have been added. (`runGraphvizCanvas` doesn't work on my machine)

### CODE REVIEW

**Comment by dented42** [comment]
I'd suggest making a 0.4.1.0 release to package as the API has been added to. Though do the dependency changes require that it be bumped up to 0.5.0.0? I'm unsure.

**Comment by raymoo** [comment]
Thanks, though I'm not sure about the version number either. It might depend on whether it can still build on the older dependencies.

**Comment by raymoo** [comment]
As for a new release I will try to get to it later this week.

**Comment by dented42** [comment]
I updated the dependencies because it wasn't building with lts-8.18. I did not change any of the lower bounds so it should still build anywhere it was already building.

**Comment by raymoo** [comment]
Were the removed imports redundant in earlier versions of base also? If some of them became redundant because of things exposed in Prelude, then it could break versions where they weren't exposed.

**Comment by dented42** [comment]
Most of them were redundant before I bumped up the lts version. The one in the last (or next to last) commit didn't pop up as redundant until after I bumped it.

**Pull request merged**
